CTDA-817/Audit for €10,000 guarantee
hmrc/common-transit-convention-traders pull request #151
Opened 2020-11-25 13:44 UTC by GeorgeColdham

# Audit for €10,000 guarantee

![Audit](https://media.giphy.com/media/l2SqhdLXcHFwHU94Q/giphy.gif)

[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-817)

2020-11-26 10:07 UTC, marcinkrykowski approved these changes

2020-11-27 10:44 UTC, RobertLaverick requested changes

2020-11-27 10:44 UTC, RobertLaverick commented on app/controllers/actions/EnsureGuaranteeAction.scala
> +class EnsureGuaranteeAction @Inject()(ensureGuaranteeService: EnsureGuaranteeService, auditService: AuditService)(
Remove the service, it isn't being used

2020-11-27 10:52 UTC, RobertLaverick approved these changes

2020-11-27 10:53 UTC, merged