CTDA-1271 added security token and notification url field definitions
hmrc/common-transit-convention-traders pull request #194
Opened 2021-05-06 14:51 UTC by RobertLaverick

2021-05-06 14:53 UTC, crystalmark approved these changes

2021-05-06 16:39 UTC, DavidGregory084 requested changes

2021-05-06 16:39 UTC, DavidGregory084 commented on resources/public/api/definition.json
> +          "type": "URL",
This should be a PPNSField

2021-05-06 16:39 UTC, DavidGregory084 commented on resources/public/api/definition.json
> +        }, {
I think there should be validation rules for this field similar to https://github.com/hmrc/goods-movement-system-haulier-api/blob/master/app/uk/gov/hmrc/goodsmovementsystemhaulierapi/platform/views/definition.scala.txt#L30

2021-05-06 16:40 UTC, DavidGregory084 commented on resources/public/api/definition.json
> +          "type": "URL",
Again see e.g. https://github.com/hmrc/goods-movement-system-haulier-api/blob/master/app/uk/gov/hmrc/goodsmovementsystemhaulierapi/platform/views/definition.scala.txt#L30

2021-05-07 09:22 UTC, DavidGregory084 approved these changes
Looks good to me 💯

2021-05-07 09:23 UTC, merged