Updated the yaml to reflect the checks that both count and page parameters are positive numbers
hmrc/common-transit-convention-traders pull request #449
Opened 2023-06-22 10:50 UTC by olakunlekuye2

2023-06-28 08:33 UTC, drnaylor-oc commented
This PR is in a slightly weird state as it has some commits that have been merged -- which it shouldn't be displaying? Anyhow -- just basing my comments on the last commit here. I'm not criticising what's been done here, just thinking out loud -- and trying to make sure every PR that is currently out has had some review.

Are the changes to the definition here necessary -- that is, should we assume that developers should know this implicitly? Or should we explicitly declare this. Should we update the examples for 400s instead to include the bad request error with the specific text for non-positive page/count, or is that superfluous?

Do we need to do any of this?

@fmcgrath do you have any thoughts on the above? You'll just want to look at https://github.com/hmrc/common-transit-convention-traders/pull/449/commits/56bb5ab63ac6e4adaec3a818f2df88c12e63a92b.

2023-06-28 09:35 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the page parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `1`) that allows the selection of a specific page from a multi-page query. If used, you must enter a positive number.

2023-06-28 09:35 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the page parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `1`) that allows the selection of a specific page from a multi-page query. If used, you must enter a positive number.

2023-06-28 09:36 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the page parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `1`) that allows the selection of a specific page from a multi-page query. If used, you must enter a positive number.

2023-06-28 09:36 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the page parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `1`) that allows the selection of a specific page from a multi-page query. If used, you must enter a positive number.

2023-06-28 09:37 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the count parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `25`) that allows the selection of the number of items per page in a multi-page query. If used, you must enter a positive number.

2023-06-28 09:37 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the count parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `25`) that allows the selection of the number of items per page in a multi-page query. If used, you must enter a positive number.

2023-06-28 09:37 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the count parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `25`) that allows the selection of the number of items per page in a multi-page query. If used, you must enter a positive number.

2023-06-28 09:37 UTC, fmcgrath commented on resources/public/api/conf/2.0/application.yaml
> +            A check is made on the count parameter to ensure it is a positive number.
Suggestion:
This is an optional query parameter (default value is `25`) that allows the selection of the number of items per page in a multi-page query. If used, you must enter a positive number.

2023-06-28 09:38 UTC, fmcgrath requested changes
Some suggestions for rewording.

2023-06-30 10:27 UTC, drnaylor-oc commented
Can you rebase your commits on top of the current main please? I'm a little concerned about my commits being there which should also be in main, yet Github hasn't picked them up (not your fault, but I don't want something to go wrong when merging).

2023-06-30 13:59 UTC, fmcgrath commented on resources/public/api/conf/1.0/application.yaml
> +                code: CLIENT_ERROR
In this block, `client id` is used but in preceding block `Client Id` is used. We need to be more consistent.

2023-06-30 14:00 UTC, fmcgrath commented on resources/public/api/conf/1.0/application.yaml
> +                  - description: Client Id Required.
Use lowercase for "required". In general, we are using sentence case.

2023-06-30 14:02 UTC, drnaylor-oc commented
Version 1 shouldn't even be in here, that'll be from previous commits.

@olakunlekuye2 can you just take your version 2 yaml file and put it on a new branch from main, then close this PR?

2023-06-30 14:03 UTC, fmcgrath commented on resources/public/api/conf/1.0/application.yaml
> +      description: An error in the supplied payload.
Would `Error in the supplied payload` be better?

2023-06-30 14:07 UTC, fmcgrath reviewed
I skimmed through the changes in the two API definition files. No major issues.

2023-06-30 14:51 UTC, closed without merging